#pragma once

#include "khg_gfx/texture.h"

#define FOREACH_TEXTURE(TEXTURE) \
  TEXTURE(NULL_TEXTURE)\
  TEXTURE(SQUARE)\
  TEXTURE(GROUND_GRASS)\
  TEXTURE(BORDER_BLACK)\
  TEXTURE(ELEMENT_BUSH_0) TEXTURE(ELEMENT_BUSH_1) TEXTURE(ELEMENT_BUSH_2) TEXTURE(ELEMENT_BUSH_3) TEXTURE(ELEMENT_BUSH_4) TEXTURE(ELEMENT_BUSH_5) TEXTURE(ELEMENT_BUSH_6) TEXTURE(ELEMENT_BUSH_7) TEXTURE(ELEMENT_BUSH_8) TEXTURE(ELEMENT_BUSH_9)\
  TEXTURE(ELEMENT_BUSH_10) TEXTURE(ELEMENT_BUSH_11) TEXTURE(ELEMENT_BUSH_12) TEXTURE(ELEMENT_BUSH_13) TEXTURE(ELEMENT_BUSH_14) TEXTURE(ELEMENT_BUSH_15) TEXTURE(ELEMENT_BUSH_16) TEXTURE(ELEMENT_BUSH_17) TEXTURE(ELEMENT_BUSH_18) TEXTURE(ELEMENT_BUSH_19)\
  TEXTURE(ELEMENT_BUSH_20) TEXTURE(ELEMENT_BUSH_21) TEXTURE(ELEMENT_BUSH_22) TEXTURE(ELEMENT_BUSH_23) TEXTURE(ELEMENT_BUSH_24) TEXTURE(ELEMENT_BUSH_25) TEXTURE(ELEMENT_BUSH_26) TEXTURE(ELEMENT_BUSH_27) TEXTURE(ELEMENT_BUSH_28) TEXTURE(ELEMENT_BUSH_29)\
  TEXTURE(ELEMENT_BUSH_30) TEXTURE(ELEMENT_BUSH_31) TEXTURE(ELEMENT_BUSH_32) TEXTURE(ELEMENT_BUSH_33) TEXTURE(ELEMENT_BUSH_34) TEXTURE(ELEMENT_BUSH_35) TEXTURE(ELEMENT_BUSH_36) TEXTURE(ELEMENT_BUSH_37) TEXTURE(ELEMENT_BUSH_38) TEXTURE(ELEMENT_BUSH_39)\
  TEXTURE(ELEMENT_BUSH_40) TEXTURE(ELEMENT_BUSH_41) TEXTURE(ELEMENT_BUSH_42) TEXTURE(ELEMENT_BUSH_43) TEXTURE(ELEMENT_BUSH_44) TEXTURE(ELEMENT_BUSH_45) TEXTURE(ELEMENT_BUSH_46) TEXTURE(ELEMENT_BUSH_47) TEXTURE(ELEMENT_BUSH_48) TEXTURE(ELEMENT_BUSH_49)\
  TEXTURE(ELEMENT_BUSH_50) TEXTURE(ELEMENT_BUSH_51) TEXTURE(ELEMENT_BUSH_52) TEXTURE(ELEMENT_BUSH_53) TEXTURE(ELEMENT_BUSH_54) TEXTURE(ELEMENT_BUSH_55) TEXTURE(ELEMENT_BUSH_56) TEXTURE(ELEMENT_BUSH_57) TEXTURE(ELEMENT_BUSH_58) TEXTURE(ELEMENT_BUSH_59)\
  TEXTURE(ELEMENT_DIRTPATCH_0) TEXTURE(ELEMENT_DIRTPATCH_1) TEXTURE(ELEMENT_DIRTPATCH_2) TEXTURE(ELEMENT_DIRTPATCH_3) TEXTURE(ELEMENT_DIRTPATCH_4) TEXTURE(ELEMENT_DIRTPATCH_5) TEXTURE(ELEMENT_DIRTPATCH_6) TEXTURE(ELEMENT_DIRTPATCH_7) TEXTURE(ELEMENT_DIRTPATCH_8) TEXTURE(ELEMENT_DIRTPATCH_9)\
  TEXTURE(ELEMENT_DIRTPATCH_10) TEXTURE(ELEMENT_DIRTPATCH_11) TEXTURE(ELEMENT_DIRTPATCH_12) TEXTURE(ELEMENT_DIRTPATCH_13) TEXTURE(ELEMENT_DIRTPATCH_14) TEXTURE(ELEMENT_DIRTPATCH_15) TEXTURE(ELEMENT_DIRTPATCH_16) TEXTURE(ELEMENT_DIRTPATCH_17) TEXTURE(ELEMENT_DIRTPATCH_18) TEXTURE(ELEMENT_DIRTPATCH_19)\
  TEXTURE(ELEMENT_DIRTPATCH_20) TEXTURE(ELEMENT_DIRTPATCH_21) TEXTURE(ELEMENT_DIRTPATCH_22) TEXTURE(ELEMENT_DIRTPATCH_23) TEXTURE(ELEMENT_DIRTPATCH_24) TEXTURE(ELEMENT_DIRTPATCH_25) TEXTURE(ELEMENT_DIRTPATCH_26) TEXTURE(ELEMENT_DIRTPATCH_27) TEXTURE(ELEMENT_DIRTPATCH_28) TEXTURE(ELEMENT_DIRTPATCH_29)\
  TEXTURE(ELEMENT_DIRTPATCH_30) TEXTURE(ELEMENT_DIRTPATCH_31) TEXTURE(ELEMENT_DIRTPATCH_32) TEXTURE(ELEMENT_DIRTPATCH_33) TEXTURE(ELEMENT_DIRTPATCH_34) TEXTURE(ELEMENT_DIRTPATCH_35) TEXTURE(ELEMENT_DIRTPATCH_36) TEXTURE(ELEMENT_DIRTPATCH_37) TEXTURE(ELEMENT_DIRTPATCH_38) TEXTURE(ELEMENT_DIRTPATCH_39)\
  TEXTURE(ELEMENT_DIRTPATCH_40) TEXTURE(ELEMENT_DIRTPATCH_41) TEXTURE(ELEMENT_DIRTPATCH_42) TEXTURE(ELEMENT_DIRTPATCH_43) TEXTURE(ELEMENT_DIRTPATCH_44) TEXTURE(ELEMENT_DIRTPATCH_45) TEXTURE(ELEMENT_DIRTPATCH_46) TEXTURE(ELEMENT_DIRTPATCH_47) TEXTURE(ELEMENT_DIRTPATCH_48) TEXTURE(ELEMENT_DIRTPATCH_49)\
  TEXTURE(ELEMENT_DIRTPATCH_50) TEXTURE(ELEMENT_DIRTPATCH_51) TEXTURE(ELEMENT_DIRTPATCH_52) TEXTURE(ELEMENT_DIRTPATCH_53) TEXTURE(ELEMENT_DIRTPATCH_54) TEXTURE(ELEMENT_DIRTPATCH_55) TEXTURE(ELEMENT_DIRTPATCH_56) TEXTURE(ELEMENT_DIRTPATCH_57) TEXTURE(ELEMENT_DIRTPATCH_58) TEXTURE(ELEMENT_DIRTPATCH_59)\
  TEXTURE(ELEMENT_GRASS_BUSH_DARK_0) TEXTURE(ELEMENT_GRASS_BUSH_DARK_1) TEXTURE(ELEMENT_GRASS_BUSH_DARK_2) TEXTURE(ELEMENT_GRASS_BUSH_DARK_3) TEXTURE(ELEMENT_GRASS_BUSH_DARK_4) TEXTURE(ELEMENT_GRASS_BUSH_DARK_5) TEXTURE(ELEMENT_GRASS_BUSH_DARK_6) TEXTURE(ELEMENT_GRASS_BUSH_DARK_7) TEXTURE(ELEMENT_GRASS_BUSH_DARK_8) TEXTURE(ELEMENT_GRASS_BUSH_DARK_9)\
  TEXTURE(ELEMENT_GRASS_BUSH_DARK_10) TEXTURE(ELEMENT_GRASS_BUSH_DARK_11) TEXTURE(ELEMENT_GRASS_BUSH_DARK_12) TEXTURE(ELEMENT_GRASS_BUSH_DARK_13) TEXTURE(ELEMENT_GRASS_BUSH_DARK_14) TEXTURE(ELEMENT_GRASS_BUSH_DARK_15) TEXTURE(ELEMENT_GRASS_BUSH_DARK_16) TEXTURE(ELEMENT_GRASS_BUSH_DARK_17) TEXTURE(ELEMENT_GRASS_BUSH_DARK_18) TEXTURE(ELEMENT_GRASS_BUSH_DARK_19)\
  TEXTURE(ELEMENT_GRASS_BUSH_DARK_20) TEXTURE(ELEMENT_GRASS_BUSH_DARK_21) TEXTURE(ELEMENT_GRASS_BUSH_DARK_22) TEXTURE(ELEMENT_GRASS_BUSH_DARK_23) TEXTURE(ELEMENT_GRASS_BUSH_DARK_24) TEXTURE(ELEMENT_GRASS_BUSH_DARK_25) TEXTURE(ELEMENT_GRASS_BUSH_DARK_26) TEXTURE(ELEMENT_GRASS_BUSH_DARK_27) TEXTURE(ELEMENT_GRASS_BUSH_DARK_28) TEXTURE(ELEMENT_GRASS_BUSH_DARK_29)\
  TEXTURE(ELEMENT_GRASS_BUSH_DARK_30) TEXTURE(ELEMENT_GRASS_BUSH_DARK_31) TEXTURE(ELEMENT_GRASS_BUSH_DARK_32) TEXTURE(ELEMENT_GRASS_BUSH_DARK_33) TEXTURE(ELEMENT_GRASS_BUSH_DARK_34) TEXTURE(ELEMENT_GRASS_BUSH_DARK_35) TEXTURE(ELEMENT_GRASS_BUSH_DARK_36) TEXTURE(ELEMENT_GRASS_BUSH_DARK_37) TEXTURE(ELEMENT_GRASS_BUSH_DARK_38) TEXTURE(ELEMENT_GRASS_BUSH_DARK_39)\
  TEXTURE(ELEMENT_GRASS_BUSH_DARK_40) TEXTURE(ELEMENT_GRASS_BUSH_DARK_41) TEXTURE(ELEMENT_GRASS_BUSH_DARK_42) TEXTURE(ELEMENT_GRASS_BUSH_DARK_43) TEXTURE(ELEMENT_GRASS_BUSH_DARK_44) TEXTURE(ELEMENT_GRASS_BUSH_DARK_45) TEXTURE(ELEMENT_GRASS_BUSH_DARK_46) TEXTURE(ELEMENT_GRASS_BUSH_DARK_47) TEXTURE(ELEMENT_GRASS_BUSH_DARK_48) TEXTURE(ELEMENT_GRASS_BUSH_DARK_49)\
  TEXTURE(ELEMENT_GRASS_BUSH_DARK_50) TEXTURE(ELEMENT_GRASS_BUSH_DARK_51) TEXTURE(ELEMENT_GRASS_BUSH_DARK_52) TEXTURE(ELEMENT_GRASS_BUSH_DARK_53) TEXTURE(ELEMENT_GRASS_BUSH_DARK_54) TEXTURE(ELEMENT_GRASS_BUSH_DARK_55) TEXTURE(ELEMENT_GRASS_BUSH_DARK_56) TEXTURE(ELEMENT_GRASS_BUSH_DARK_57) TEXTURE(ELEMENT_GRASS_BUSH_DARK_58) TEXTURE(ELEMENT_GRASS_BUSH_DARK_59)\
  TEXTURE(ELEMENT_GRASS_BUSH_REG_0) TEXTURE(ELEMENT_GRASS_BUSH_REG_1) TEXTURE(ELEMENT_GRASS_BUSH_REG_2) TEXTURE(ELEMENT_GRASS_BUSH_REG_3) TEXTURE(ELEMENT_GRASS_BUSH_REG_4) TEXTURE(ELEMENT_GRASS_BUSH_REG_5) TEXTURE(ELEMENT_GRASS_BUSH_REG_6) TEXTURE(ELEMENT_GRASS_BUSH_REG_7) TEXTURE(ELEMENT_GRASS_BUSH_REG_8) TEXTURE(ELEMENT_GRASS_BUSH_REG_9)\
  TEXTURE(ELEMENT_GRASS_BUSH_REG_10) TEXTURE(ELEMENT_GRASS_BUSH_REG_11) TEXTURE(ELEMENT_GRASS_BUSH_REG_12) TEXTURE(ELEMENT_GRASS_BUSH_REG_13) TEXTURE(ELEMENT_GRASS_BUSH_REG_14) TEXTURE(ELEMENT_GRASS_BUSH_REG_15) TEXTURE(ELEMENT_GRASS_BUSH_REG_16) TEXTURE(ELEMENT_GRASS_BUSH_REG_17) TEXTURE(ELEMENT_GRASS_BUSH_REG_18) TEXTURE(ELEMENT_GRASS_BUSH_REG_19)\
  TEXTURE(ELEMENT_GRASS_BUSH_REG_20) TEXTURE(ELEMENT_GRASS_BUSH_REG_21) TEXTURE(ELEMENT_GRASS_BUSH_REG_22) TEXTURE(ELEMENT_GRASS_BUSH_REG_23) TEXTURE(ELEMENT_GRASS_BUSH_REG_24) TEXTURE(ELEMENT_GRASS_BUSH_REG_25) TEXTURE(ELEMENT_GRASS_BUSH_REG_26) TEXTURE(ELEMENT_GRASS_BUSH_REG_27) TEXTURE(ELEMENT_GRASS_BUSH_REG_28) TEXTURE(ELEMENT_GRASS_BUSH_REG_29)\
  TEXTURE(ELEMENT_GRASS_BUSH_REG_30) TEXTURE(ELEMENT_GRASS_BUSH_REG_31) TEXTURE(ELEMENT_GRASS_BUSH_REG_32) TEXTURE(ELEMENT_GRASS_BUSH_REG_33) TEXTURE(ELEMENT_GRASS_BUSH_REG_34) TEXTURE(ELEMENT_GRASS_BUSH_REG_35) TEXTURE(ELEMENT_GRASS_BUSH_REG_36) TEXTURE(ELEMENT_GRASS_BUSH_REG_37) TEXTURE(ELEMENT_GRASS_BUSH_REG_38) TEXTURE(ELEMENT_GRASS_BUSH_REG_39)\
  TEXTURE(ELEMENT_GRASS_BUSH_REG_40) TEXTURE(ELEMENT_GRASS_BUSH_REG_41) TEXTURE(ELEMENT_GRASS_BUSH_REG_42) TEXTURE(ELEMENT_GRASS_BUSH_REG_43) TEXTURE(ELEMENT_GRASS_BUSH_REG_44) TEXTURE(ELEMENT_GRASS_BUSH_REG_45) TEXTURE(ELEMENT_GRASS_BUSH_REG_46) TEXTURE(ELEMENT_GRASS_BUSH_REG_47) TEXTURE(ELEMENT_GRASS_BUSH_REG_48) TEXTURE(ELEMENT_GRASS_BUSH_REG_49)\
  TEXTURE(ELEMENT_GRASS_BUSH_REG_50) TEXTURE(ELEMENT_GRASS_BUSH_REG_51) TEXTURE(ELEMENT_GRASS_BUSH_REG_52) TEXTURE(ELEMENT_GRASS_BUSH_REG_53) TEXTURE(ELEMENT_GRASS_BUSH_REG_54) TEXTURE(ELEMENT_GRASS_BUSH_REG_55) TEXTURE(ELEMENT_GRASS_BUSH_REG_56) TEXTURE(ELEMENT_GRASS_BUSH_REG_57) TEXTURE(ELEMENT_GRASS_BUSH_REG_58) TEXTURE(ELEMENT_GRASS_BUSH_REG_59)\
  TEXTURE(NUM_TEXTURES)

#define GENERATE_TEXTURE_ENUM(ENUM) ENUM,
#define GENERATE_TEXTURE_STRING(STRING) #STRING,

typedef enum {
  FOREACH_TEXTURE(GENERATE_TEXTURE_ENUM)
} texture_id;

#define TEXTURE_STRINGS (char *[]){ FOREACH_TEXTURE(GENERATE_TEXTURE_STRING) }
#define TEXTURE_STRINGS_SIZE sizeof(TEXTURE_STRINGS) / sizeof(TEXTURE_STRINGS[0])

typedef struct texture_asset {
  char tex_filepath[128];
  int tex_width;
  int tex_height;
} texture_asset;

const gfx_texture generate_texture(const char *filepath, const float width, const float height);
const bool check_texture_loaded(const unsigned int tex_id);
const unsigned int get_tex_id_from_string(const char *tex_key);

const gfx_texture get_or_add_texture(const unsigned int tex_id);
const gfx_texture get_or_add_texture_from_string(const char *tex_key);

void generate_textures(void);
void reset_textures(void);

