name: Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install cmake deps
      run: |
        sudo apt update
        wget http://mirrors.kernel.org/ubuntu/pool/main/libi/libidn/libidn11_1.33-2.2ubuntu2_amd64.deb
        sudo apt install ./libidn11_1.33-2.2ubuntu2_amd64.deb

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.5.x'
    - name: Use cmake
      run: cmake --version

    - name: Run build script
      run: |
        mkdir build
        ./build.sh build

    - name: Check build status
      run: |
        if [ ! -f "build/executable.exe" ]; then
          echo "Build failed: executable.exe not found."
          exit 1
        fi
