name: Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: cmake/setup-cmake@v3
      with:
        cmake-version: 3.26.4

    - name: Run build script
      run: ./build.sh build

    - name: Check build status
      run: |
        if [ ! -f "build/executable.exe" ]; then
          echo "Build failed: executable.exe not found."
          exit 1
        fi
