name: Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CMake 3.5
      run: |
        # Install necessary dependencies
        sudo apt-get update
        sudo apt-get install -y wget tar

        # Remove any existing CMake installation
        sudo apt-get remove -y cmake || true

        # Download and install CMake 3.5.2
        wget https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz
        tar -xzvf cmake-3.5.2-Linux-x86_64.tar.gz
        sudo cp -r cmake-3.5.2-Linux-x86_64/* /usr/local/

    - name: Verify CMake version
      run: cmake --version

    - name: Run build script
      run: ./build.sh

    - name: Check build status
      run: |
        if [ ! -f "build/executable.exe" ]; then
          echo "Build failed: executable.exe not found."
          exit 1
        fi
