name: Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.5.x'
    - name: Use cmake
      run: cmake --version

    - name: Run build script
      run: ./build.sh

    - name: Check build status
      run: |
        if [ ! -f "build/executable.exe" ]; then
          echo "Build failed: executable.exe not found."
          exit 1
        fi
