name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install deps
      run: |
        sudo apt update
        wget http://mirrors.kernel.org/ubuntu/pool/main/libi/libidn/libidn11_1.33-2.2ubuntu2_amd64.deb
        sudo apt install ./libidn11_1.33-2.2ubuntu2_amd64.deb
        sudo apt-get install libxrandr-dev libx11-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16.x'

    - name: Use cmake
      run: cmake --version

    - name: Run build script
      run: |
        mkdir build
        ./build.sh build

    - name: Check build status (executable)
      run: |
        if [ ! -f "build/executable" ]; then
          echo "Build failed: executable not found."
          exit 1
        fi

    - name: Check build status (test_runner)
      run: |
        if [ ! -f "build/test_runner" ]; then
          echo "Build failed: test_runner not found."
          exit 1
        fi

  test:
    name: Test Check
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install deps
      run: |
        sudo apt update
        wget http://mirrors.kernel.org/ubuntu/pool/main/libi/libidn/libidn11_1.33-2.2ubuntu2_amd64.deb
        sudo apt install ./libidn11_1.33-2.2ubuntu2_amd64.deb
        sudo apt-get install libxrandr-dev libx11-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16.x'

    - name: Run tests
      run: |
        mkdir build
        cd build
        ./build.sh test
        if [ $? -ne 0 ]; then
          echo "Tests failed."
          exit 1
        fi
